// Mocks generated by Mockito 5.4.0 from annotations
// in anime_list/test/features/anime_list/presentation/pages/anime_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:anime_list/features/anime_list/domain/entities/anime.dart'
    as _i4;
import 'package:anime_list/features/anime_list/domain/usecases/get_top_anime.dart'
    as _i2;
import 'package:anime_list/features/anime_list/presentation/bloc/anime_list_bloc.dart'
    as _i3;
import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTopAnime_0 extends _i1.SmartFake implements _i2.GetTopAnime {
  _FakeGetTopAnime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAnimeListState_1 extends _i1.SmartFake
    implements _i3.AnimeListState {
  _FakeAnimeListState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AnimeListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnimeListBloc extends _i1.Mock implements _i3.AnimeListBloc {
  MockAnimeListBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTopAnime get getTopAnime => (super.noSuchMethod(
        Invocation.getter(#getTopAnime),
        returnValue: _FakeGetTopAnime_0(
          this,
          Invocation.getter(#getTopAnime),
        ),
      ) as _i2.GetTopAnime);

  @override
  List<_i4.Anime> get allAnimeList => (super.noSuchMethod(
        Invocation.getter(#allAnimeList),
        returnValue: <_i4.Anime>[],
      ) as List<_i4.Anime>);

  @override
  set allAnimeList(List<_i4.Anime>? _allAnimeList) => super.noSuchMethod(
        Invocation.setter(
          #allAnimeList,
          _allAnimeList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get currentPage => (super.noSuchMethod(
        Invocation.getter(#currentPage),
        returnValue: 0,
      ) as int);

  @override
  set currentPage(int? _currentPage) => super.noSuchMethod(
        Invocation.setter(
          #currentPage,
          _currentPage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasReachedMax => (super.noSuchMethod(
        Invocation.getter(#hasReachedMax),
        returnValue: false,
      ) as bool);

  @override
  set hasReachedMax(bool? _hasReachedMax) => super.noSuchMethod(
        Invocation.setter(
          #hasReachedMax,
          _hasReachedMax,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AnimeListState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAnimeListState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AnimeListState);

  @override
  _i5.Stream<_i3.AnimeListState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.AnimeListState>.empty(),
      ) as _i5.Stream<_i3.AnimeListState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i3.AnimeListEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i3.AnimeListEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.AnimeListState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i3.AnimeListEvent>(
    _i6.EventHandler<E, _i3.AnimeListState>? handler, {
    _i6.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i6.Transition<_i3.AnimeListEvent, _i3.AnimeListState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onChange(_i6.Change<_i3.AnimeListState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
