// Mocks generated by Mockito 5.4.0 from annotations
// in anime_list/test/features/anime_list/data/repositories/anime_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:anime_list/features/anime_list/data/datasources/anime_remote_data_source.dart'
    as _i2;
import 'package:anime_list/features/anime_list/data/models/anime_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AnimeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnimeRemoteDataSource extends _i1.Mock
    implements _i2.AnimeRemoteDataSource {
  MockAnimeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AnimeModel>> getTopAnime(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopAnime,
          [page],
        ),
        returnValue: _i3.Future<List<_i4.AnimeModel>>.value(<_i4.AnimeModel>[]),
      ) as _i3.Future<List<_i4.AnimeModel>>);
}
